name: Build and Publish

on:
    push:
        branches:
            - main

permissions:
    contents: write
    pull-requests: write

jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: cp README.md package/README.md
            - uses: pnpm/action-setup@v4
              with:
                  version: 8
            - uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
                  registry-url: 'https://registry.npmjs.org'
                  cache: "pnpm"
            - run: pnpm install --frozen-lockfile --filter ./package
            - run: pnpm --filter ./package run build
            - run: cd package && npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
